### PR TITLE
Add "Svelte Routing"

### PR DESCRIPTION
**Pull request by YogliB**
I wasn't sure under what category to put this, so feel free to edit this.

### CODE REVIEW

**Comment by xamgore** [comment]
@YogliB could you also add the following packages?

1. https://github.com/ItalyPaleAle/svelte-spa-router — inspired by svelte-routing, supports hash-based routing
2. https://github.com/kazzkiq/svero
1. https://visionmedia.github.io/page.js/

**Comment by YogliB** [comment]
> @YogliB would you be so kind to also add the following packages?
> 
> 1. https://github.com/ItalyPaleAle/svelte-spa-router — inspired by svelte-routing, supports hash-based routing
> 2. https://github.com/kazzkiq/svero

Of course :)

**Comment by CalvinWalzel** [comment]
@YogliB You deleted an entry. Is that intended? Then I'll merge this.

**Comment by YogliB** [comment]
@CalvinWalzel
Not intended, I'll fix it.
Thanks!

**Pull request closed without merging**
